### ISSUE TITLE
[SECONDARY FEATURE] Upvote/Downvote Button

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Frontend#10]
### User Story
As a student I want to have an upvote/downvote Button next to the professor's name on the class search results page so that I can provide my input on the professor and others can see it.

### Technical Tasks:
- You don't need to worry about checking if it's the correct page. This is handled in #8. Just assume every page is valid.
- On page load, get a list of elements with professor names in the dom. Selecting by class may help with this. (This task is repeated in #9, implement your own method as well and we'll choose the best from the two) ![image](https://user-images.githubusercontent.com/19192562/188212201-bf798bb1-079a-4257-8465-e44a4243f54c.png)
- Inject upvote/downvote buttons next to the professor name (preferrably to the left)
- Add event listeners to the buttons that log when they are pressed and for which professor

### Acceptance Criteria
- When the user has class search page open, the extension injects upvote/downvote buttons next to professor names
- On click, the button logs in the console the professor name and whether upvote or downvote was pressed

**Comment by misslame** [comment]
Front end
