### ISSUE TITLE
[SECONDARY FEATURE] Popup Search Bar

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Frontend#11]
### User Story
As a student I want a search bar that'll help me find any professor on RMP.

### Technical Task:
- Create search state in App.tsx
- Setup a search bar component with search button and add it to App.tsx.
- Search should run when search button or "enter" key is pressed
- Link text in search bar to search state
- When button is pressed/"enter" pressed, log the text in the box in the console
- Use useContext (OPTIONAL)

### Acceptance Criteria:
- Search bar appears in popup with search button
- Upon pressing enter or pressing the search button, the state is passed to the parent component
- Searches are logged to the console

**Comment by jaroonl** [comment]
im having a bit of trouble with how to pass the state to the parent component when pressing enter (and also binding the search button to actually have functionality)
