### ISSUE TITLE
[ENHANCEMENT] Toggle Enabled Button

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Frontend#13]
### User Story
As a user, I want to be able to click a toggle button so that I can be able to quickly toggle the extension on or off.

### Technical Tasks:
- Add a toggle button to the top right of the extension popup
- Log the state when the button is toggled
- State should be elevated and component placed in popup(App.tsx)

### Acceptance Criteria:
- Toggle button displays in top right of popup
- State logs when button is toggled
- Component passed state changes to parents

**Comment by ighmaZ** [comment]
hi , i wanna contribute
