### ISSUE TITLE
[ENHANCEMENT] Settings Panel

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Frontend#14]
### User Story
As a student, I want a settings panel to have a centralized location to edit the extensions' settings for ease of use.

### Technical Tasks:
- Add a settings button at the top right of the popup (App.tsx)
- Use inline styling to format filler content
- Clicking the button opens a new panel on top of the original popup content with random text (temporary)
- Add a close button to close the settings panel material

### Acceptance Criteria:
- Settings button shows in the popup and opens a settings panel
- Settings panel has a close button that closes the panel on-click

**Comment by misslame** [comment]
@wheatleyinabox  Please link the PR to the issue
