### ISSUE TITLE
[Primary Feature] Every Component needs to call the Backend Data on its Professor

### ISSUE THREAD

**Issue by tapatiohaxx** [BroncoDirectMe/Frontend#37]
### User Story
As a developer, I want to ensure that work on the backend and frontend work together.

### Technical Tasks
- Find a way to conveniently link all of the data on a professor from the database to the client's frontend.

### Acceptance Criteria
- We should see that every component grabs data from the backend to show the correct information.

**Comment by misslame** [comment]
This is vague and could potentially be written as a task instead of a story.
