### ISSUE TITLE
[PRIMARY FEATURE] Report Missing Professor Button

### ISSUE THREAD

**Issue by tapatiohaxx** [BroncoDirectMe/Frontend#38]
### User Story
As a user, I should be able to report a missing professor if he/she is not picked up automatically by the query (ie not in the database).

### Technical Tasks
- Create a button that says "report missing professor"
- Make a form that allows a user to type the name and major that the teacher teaches.

### Acceptance Criteria
- There should be a button that allows you to submit a request to add a professor that's not on the list.

**Comment by misslame** [comment]
This should add the professor that is not found automatically to the database with blank information.

**Comment by misslame** [comment]
@alinz22 reach out to @wheatleyinabox  if you need help on this. I may ask you to assign val to the task if you two are up to working together on it. Otherwise, it is your deal. Good luck!
