### ISSUE TITLE
[PROJECT HEALTH] Implement github webhooks for repository change notifications - Frontend

### ISSUE THREAD

**Issue by misslame** [BroncoDirectMe/Frontend#4]
### User Story
As a Project Contributor, I should be able to quickly be notified of repository changes on the project's preferred communication platform, Discord, so that I can stay up to date on project direction and progress. 

### Technical Task:
Implement webhooks for discord to notify the discord in a text channel in the project discord server. 

### Acceptance Criteria:
- Repository pull requests, stars, watch, fork, pushes, new branches, etc are posted in the discord server. (#github-updates)

### Related Issues: 
- [Backend Issue #3](https://github.com/BroncoDirectMe/Backend/issues/3)

**Comment by PattyCakesxD** [comment]
The github webhook is successfully connected to the project's discord. Any changes to the repository will be posted in #github-updates.
