### ISSUE TITLE
[PROJECT HEALTH] Set up Continuous Integration Automatic Builds

### ISSUE THREAD

**Issue by misslame** [BroncoDirectMe/Frontend#5]
### User Story
As an project contributor, I should be able to feel more secure with the current state of the project that it is errorless & may be deployed so that I can participate in producing quality project updates. 

### Technical Task:
Please refer to this: https://medium.com/slido-dev-blog/chrome-extensions-and-continuous-integration-392206f7e414
If CI automatic builds are doable. This may require further questions and discussion. 

### Acceptance Criteria:
- CI is implemented

**Comment by tapatiohaxx** [comment]
If we are to commit to CI, is there going to be a shared environment that we could build the script off of? I feel like it may be advantageous to force everyone to use some sort of linux image so that we could try to implement tutorials easily and not have people using different systems. I don't know if multiple people will eventually take this task over (or will even be allowed to) and force uniformity in our process to minimize problems with the CI process.

**Comment by misslame** [comment]
How would there be problems in our CI process without local set up uniformity? I am unsure what you mean. 

I think I linked an example here for chrome extensions to auto deploy/update after checks. This does not require any uniformity on local debugging, testing, etc. This also doesn't require people who want to use the extension any specific local set up either.

**Comment by ZombiMigz** [comment]
This could potentially be applied in the backend if/when we run into compatibility issues. For the chrome extension though I think we're good.

**Comment by tapatiohaxx** [comment]
@misslame I saw this (https://circleci.com/blog/continuously-deploy-a-chrome-extension/) in the post you shared from medium. I read it and it had a configuration listed that had a standard production environment listed as <code> Ubuntu 16.04</code> . I just wanted to know if we were going to do something similar in the beginnings or as we go.

**Comment by ZombiMigz** [comment]
> @misslame I saw this (https://circleci.com/blog/continuously-deploy-a-chrome-extension/) in the post you shared from medium. I read it and it had a configuration listed that had a standard production environment listed as <code> Ubuntu 16.04</code> . I just wanted to know if we were going to do something similar in the beginnings or as we go.

I'll look into it, but I think it should be fine. Chrome extensions build to files and I'm assuming CircleCI just deploys them to the chrome store.
