### ISSUE TITLE
[PRIMARY FEATURE] Identify BroncoDirect Page

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Frontend#8]
### User Story
As a student, I want the extension to only run on BroncoDirect and only on specific pages so it doesn't interfere with other sites.

### Technical Task:
- Identify whether site is BroncoDirect on load
- Identify which page of BroncoDirect is being loaded (particularly if it is the course search result page under Classes&Registration>Class Search> Search)

### Acceptance Criteria:
- Upon page being loaded, extension should log whether or not the page is BroncoDirect in the console
- Upon page load, extension should log whether or not page is BroncoDirect in the console

#### Related Issues: #2

**Comment by misslame** [comment]
May require you to communicate with issue #10 assignee to ensure things work together after merge. :D
